version: "3"
services:
  web:
    build: .
    container_name: web
    restart: always
    environment:
      - NODE_ENV
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ".:/code"
  pg:
    image: postgres
    container_name: postgres
    restart: always
  redis:
    image: redis
    container_name: redis
    restart: always